# Tensorflow Tutorial

## Import Libraries

In [1]:
import tensorflow as tf
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

## Generate Synthetic Dataset

In [2]:
X, y = make_classification(
    n_samples=1000,
    n_features=2,
    n_informative=2,
    n_redundant=0,
    n_repeated=0,
    n_classes=2,
    random_state=42
)

In [3]:
X

array([[-0.99910178, -0.66386   ],
       [ 1.24668618,  1.15359685],
       [ 0.96277683,  0.85939747],
       ...,
       [-0.10126746, -1.59017563],
       [ 0.64376105, -0.78053855],
       [ 0.69852984, -1.27940455]])

In [4]:
y

array([1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,

## Train Test Split

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## Standardize the Dataset

In [6]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

## Builing Model

In [7]:
# Define a simple neural network model
model = tf.keras.Sequential([

    # Input layer: specify the shape of input data
    # Here, shape=(2,) means each input sample has 2 features
    # This is important so the model knows what kind of data to expect
    tf.keras.Input(shape=(2,)),

    # Dense layer: a fully connected layer with 1 neuron
    # 'activation="sigmoid"' means the output will be between 0 and 1
    # This is typical for binary classification problems (0 or 1)
    tf.keras.layers.Dense(1, activation='sigmoid')
])


In [8]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3 (12.00 B)

 Trainable params: 3 (12.00 B)

 Non-trainable params: 0 (0.00 B)

### Common `activation` options in `tf.keras`

#### What Activations Do
Activation functions introduce **non-linearity** into neural networks, enabling them to learn complex patterns.  
They’re applied to each layer’s output to control what gets passed to the next layer.

#### Common Activation Functions

| Activation | Description | Typical Use Case |
|-------------|-------------|------------------|
| `linear` | Returns input as-is (`f(x) = x`). | Regression outputs or identity mapping. |
| `sigmoid` | Maps values between 0 and 1. | Binary classification output. |
| `softmax` | Converts logits into probabilities that sum to 1. | Multiclass classification output. |
| `tanh` | Maps values between -1 and 1. | Hidden layers; when data is centered around zero. |
| `relu` | Rectified Linear Unit: `f(x) = max(0, x)`. | Most common for hidden layers. |


**Example:**
```python
model = tf.keras.Sequential([
    tf.keras.Input(shape=(2,)),
    tf.keras.layers.Dense(8, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])
```

In [10]:
# Compile the model to prepare it for training
model.compile(
    # Optimizer: controls how the model updates its weights during training
    # 'adam' is a popular choice that adapts the learning rate automatically
    optimizer='adam',

    # Loss function: measures how far the model's predictions are from the true labels
    # 'binary_crossentropy' is used for binary classification problems (0 or 1)
    # The model tries to minimize this loss during training
    loss='binary_crossentropy',

    # Metrics: what we want to track and report during training
    # 'accuracy' shows the proportion of correct predictions
    metrics=['accuracy']
)

### Common `optimizer` and `loss` options in `tf.keras`

#### Optimizers
Optimizers control how the model updates its weights during training. Some common ones are:

| Optimizer | Description |
|-----------|-------------|
| `SGD` | Stochastic Gradient Descent. Simple, standard optimizer. Can use `momentum` to speed up convergence. |
| `RMSprop` | Good for recurrent neural networks. Adapts learning rates per parameter. |
| `Adam` | Popular default optimizer. Combines benefits of RMSprop and momentum. |
| `Adagrad` | Adapts learning rate based on frequency of updates. Good for sparse data. |
| `Adadelta` | Similar to Adagrad but doesn’t accumulate past squared gradients indefinitely. |
| `Nadam` | Adam optimizer with Nesterov momentum. |

**Example:**
```python
model.compile(optimizer='SGD', loss='binary_crossentropy', metrics=['accuracy'])
```

#### Loss Functions

The loss function measures how well the model predicts the target values. Some common ones:

##### For Classification
| Loss | Use Case |
|------|---------|
| `binary_crossentropy` | Binary classification (0 or 1). |
| `categorical_crossentropy` | Multi-class classification with one-hot encoded labels. |
| `sparse_categorical_crossentropy` | Multi-class classification with integer labels. |
| `hinge` | For binary classification using “maximum-margin” (SVM-style). |

##### For Regression
| Loss | Use Case |
|------|---------|
| `mean_squared_error (MSE)` | Standard regression loss (squared difference). |
| `mean_absolute_error (MAE)` | Measures absolute difference; less sensitive to outliers. |
| `mean_absolute_percentage_error (MAPE)` | Percentage-based error for regression tasks. |
| `huber` | Combination of MSE and MAE; robust to outliers. |

**Notes:**
- You can also use a **custom loss function** by passing a Python function.  
- Common metrics to track include `'accuracy'`, `'Precision'`, `'Recall'`, `'AUC'`, etc.


## Training Model

In [11]:
# Train the model on the training data
history = model.fit(
    X_train,           # Input features for training
    y_train,           # True labels for each training sample
    epochs=50,         # Number of times the model will see the entire training dataset
                       # More epochs can improve learning but too many may cause overfitting
    batch_size=16,     # Number of samples the model processes before updating weights
                       # Smaller batch sizes can make learning more stable but slower
    validation_split=0.1  # Reserve 10% of the training data to evaluate the model during training
                          # This helps monitor if the model is overfitting
)

Epoch 1/50
45/45 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.1667 - loss: 1.2953 - val_accuracy: 0.2125 - val_loss: 1.1908
Epoch 2/50
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1653 - loss: 1.2680 - val_accuracy: 0.2125 - val_loss: 1.1678
Epoch 3/50
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1694 - loss: 1.2417 - val_accuracy: 0.2000 - val_loss: 1.1447
Epoch 4/50
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1708 - loss: 1.2151 - val_accuracy: 0.2000 - val_loss: 1.1228
Epoch 5/50
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1736 - loss: 1.1892 - val_accuracy: 0.2000 - val_loss: 1.1008
Epoch 6/50
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1764 - loss: 1.1637 - val_accuracy: 0.2000 - val_loss: 1.0789
Epoch 7/50
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1806 - loss: 1.1384 - val_accuracy: 0.2000 - val_loss: 1.0577
Epoch 8/50
45/45 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.1806 - loss: 1.1137 - val_accuracy: 0.1750 - val_loss:

## Model Evaluation

In [12]:
loss, accuracy = model.evaluate(X_test, y_test)

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8750 - loss: 0.5015  


In [13]:
from sklearn.metrics import classification_report, confusion_matrix

# Get predicted probabilities
y_pred_prob = model.predict(X_test)

# Convert probabilities to binary predictions (0 or 1)
y_pred = (y_pred_prob > 0.5).astype(int)

# Print detailed evaluation
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step 
[[91 10]
 [15 84]]
              precision    recall  f1-score   support

           0       0.86      0.90      0.88       101
           1       0.89      0.85      0.87        99

    accuracy                           0.88       200
   macro avg       0.88      0.87      0.87       200
weighted avg       0.88      0.88      0.87       200

